# Generated by Django 4.1.2 on 2022-10-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojaapp', '0003_rename_visualização_produto_visualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
