# Generated by Django 4.1.2 on 2022-10-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0004_pedido_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_order',
            name='user',
        ),
    ]
