# Generated by Django 4.1.2 on 2022-10-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0005_remove_pedido_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro'),
        ),
    ]
